/*
  JavaScript is out of scope for this assignment.
  You should not modify anything inside this file.
*/

const movies = [
  {
    id: 1,
    name: "Shang-Chi and the Legend of the Ten Rings",
    year: 2021,
    genre: "Action, Adventure, Fantasy",
    director: "Destin Daniel Cretton",
    writer: "Dave Callaham, Destin Daniel Cretton, Andrew Lanham",
    actors: "Simu Liu, Awkwafina, Tony Chiu-Wai Leung",
    description: "Shang-Chi, a martial artist, lives a quiet life after he leaves his father and the shadowy Ten Rings organisation behind. Years later, he is forced to confront his past when the Ten Rings attack him.",
    releaseDate: "03 Sep 2021",
    image: "images/Shang-Chi.jpg",
    video: "https://www.youtube.com/embed/8YjFbMbfXaQ?controls=0&rel=0&autoplay=1&showinfo=0&playlist=8YjFbMbfXaQ",
    price: 2.49,
  },
  {
    id: 2,
    name: "PAW Patrol: The Movie",
    year: 2021,
    genre: "Animation, Adventure, Comedy",
    director: "Cal Brunker",
    writer: "Bob Barlen, Cal Brunker, Billy Frolick",
    actors: "Iain Armitage, Will Brisbin, Ron Pardo",
    description: "When their biggest rival, Humdinger, starts wreaking havoc as the mayor of Adventure City, Ryder and everyone's favorite heroic pups kick into high gear to face the challenge. Armed with exciting new gadgets and gear, the PAW Patrol joins forces with a savvy dachshund to save the citizens of Adventure City.",
    releaseDate: "20 Aug 2021",
    image: "images/paw_patrol.jpg",
    video: "https://www.youtube.com/embed/LRMTr2VZcr8?controls=0&rel=0&autoplay=1&showinfo=0&playlist=LRMTr2VZcr8",
    price: 2.99,
  },
  {
    id: 3,
    name: "Spider-Man 3",
    year: 2007,
    genre: "Action, Adventure, Sci-Fi",
    director: "Sam Raimi",
    writer: "Sam Raimi, Ivan Raimi, Alvin Sargent",
    actors: "Tobey Maguire, Kirsten Dunst, Topher Grace",
    description:
      "Peter Parker becomes one with a symbiotic alien that bolsters his Spider-Man avatar and affects his psyche. He also has to deal with Sandman and maintain a fragmented relationship with Mary Jane.",
    releaseDate: "04 May 2007",
    image: "images/spider-man3.jpg",
    video: "https://www.youtube.com/embed/e5wUilOeOmg?controls=0&rel=0&autoplay=1&showinfo=0&playlist=e5wUilOeOmg",
    price: 0.50,
  },
  {
    id: 4,
    name: "Don't Breathe",
    year: 2016,
    genre: "Crime, Horror, Thriller",
    director: "Fede Alvarez",
    writer: "Fede Alvarez, Rodo Sayagues",
    actors: "Stephen Lang, Jane Levy, Dylan Minnette",
    description:
      "Three delinquents break into the house of Norman, a Gulf War veteran who is blind, to steal his money. However, much to their horror, they discover that Norman is not as defenceless as he seems.",
    releaseDate: "26 Aug 2016",
    image: "images/dont-breathe.jpg",
    video: "https://www.youtube.com/embed/76yBTNDB6vU?controls=0&rel=0&autoplay=1&showinfo=0&playlist=76yBTNDB6vU",
    price: 1.29,
  },
  {
    id: 5,
    name: "The Dark Knight",
    year: 2008,
    genre: "Action, Crime, Drama",
    director: "Christopher Nolan",
    writer: "Jonathan Nolan, Christopher Nolan, David S. Goyer",
    actors: "Christian Bale, Heath Ledger, Aaron Eckhart",
    description:
      "After Gordon, Dent and Batman begin an assault on Gotham's organised crime, the mobs hire the Joker, a psychopathic criminal mastermind who offers to kill Batman and bring the city to its knees.",
    releaseDate: "18 Jul 2008",
    image: "images/Dark-Knight.jpg",
    video: "https://www.youtube.com/embed/LDG9bisJEaI?controls=0&rel=0&autoplay=1&showinfo=0&playlist=LDG9bisJEaI",
    price: 2.99,
  },
  {
    id: 6,
    name: "The Matrix",
    year: 1999,
    genre: "Action, Sci-Fi",
    director: "Lana Wachowski, Lilly Wachowski",
    writer: "Lilly Wachowski, Lana Wachowski",
    actors: "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
    description:
      "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
    releaseDate: "31 Mar 1999",
    image: "images/matrix.jpg",
    video: "https://www.youtube.com/embed/vKQi3bBA1y8?controls=0&rel=0&autoplay=1&showinfo=0&playlist=vKQi3bBA1y8",
    price: 1.79,
  },
  {
    id: 7,
    name: "Demonic",
    year: 2021,
    genre: "Horror",
    director: "Neill Blomkamp",
    writer: "Neill Blomkamp",
    actors: "Andrea Agur, Nathalie Boltt, Terry Chen",
    description:
      "A young woman unleashes terrifying demons when supernatural forces at the root of a decades-old rift between mother and daughter are ruthlessly revealed.",
    releaseDate: "20 Aug 2021",
    image: "images/demonic.jpg",
    video: "https://www.youtube.com/embed/EYXLKC5xd7Q?controls=0&rel=0&autoplay=1&showinfo=0&playlist=EYXLKC5xd7Q",
    price: 0.49,
  },
  {
    id: 8,
    name: "The Power of the Dog",
    year: 2021,
    genre: "Drama, Romance, Western",
    director: "Jane Campion",
    writer: "Jane Campion, Thomas Savage",
    actors: "Benedict Cumberbatch, Kirsten Dunst, Jesse Plemons",
    description:
      "Charismatic rancher Phil Burbank inspires fear and awe in those around him. When his brother brings home a new wife and her son, Phil torments them until he finds himself exposed to the possibility of love.",
    releaseDate: "01 Dec 2021",
    image: "images/the-power-of-the-dog.jpg",
    video: "https://www.youtube.com/embed/LRDPo0CHrko?controls=0&rel=0&autoplay=1&showinfo=0&playlist=LRDPo0CHrko",
    price: 1.79,
  },
  {
    id: 9,
    name: "Spider-Man 2",
    year: 2004,
    genre: "Action, Adventure, Sci-Fi",
    director: "Sam Raimi",
    writer: "Stan Lee, Steve Ditko, Alfred Gough",
    actors: "Tobey Maguire, Kirsten Dunst, Alfred Molina",
    description:
      "Peter Parker is dissatisfied with life when he loses his job, the love of his life, Mary Jane, and his powers. Amid all the chaos, he must fight Doctor Octavius who threatens to destroy New York City.",
    releaseDate: "30 Jun 2004",
    image: "images/spiderman-2.jpg",
    video: "https://www.youtube.com/embed/enmFqm_N_ZE?controls=0&rel=0&autoplay=1&showinfo=0&playlist=enmFqm_N_ZE",
    price: 2.49,
  },
  {
    id: 10,
    name: "Wrath of Man",
    year: 2021,
    genre: "Action, Crime, Thriller",
    director: "Guy Ritchie",
    writer: "Nicolas Boukhrief, Éric Besnard, Guy Ritchie",
    actors: "Jason Statham, Holt McCallany, Josh Hartnett",
    description: "H is a mysterious man who starts working for a cash moving truck company. He becomes known for using amazing precision and dexterity to neutralise robbers. However, H is actually out for revenge.",
    releaseDate: "07 May 2021",
    image: "images/wrath-of-man.jpg",
    video: "https://www.youtube.com/embed/EFYEni2gsK0?controls=0&rel=0&autoplay=1&showinfo=0&playlist=EFYEni2gsK0",
    price: 0.49,
  },
  {
    id: 11,
    name: "Shrek",
    year: 2005,
    genre: "Adventure, Animation",
    director: "Andrew Adamson, Vicky Jenson",
    writer: "William Seig, Ted Elliot",
    actors: "Mike Myers, Eddie Murphy, Cameron Diaz",
    description: "A mean lord exiles fairytale creatures to the swamp of a grumpy ogre, who must go on a quest and rescue a princess for the lord in order to get his land back.",
    releaseDate: "2005",
    image: "images/shrek.jpg",
    video: "https://www.youtube.com/embed/CwXOrWvPBPk?controls=0&rel=0&autoplay=1&showinfo=0&playlist=CwXOrWvPBPk",
    price: 1.79,
  },
  {
    id: 12,
    name: "Bee Movie",
    year: 2007,
    genre: "Animation",
    director: "Simon J Smith, Steve Hickner",
    writer: "Jerry Seinfield, Spike Feresten, Barry Marder",
    actors: "Jerry Seinfield, Renee Zellweger, Matthew Broderick",
    description: "Barry B. Benson, a bee just graduated from college, is disillusioned at his lone career choice: making honey. On a special trip outside the hive, Barry's life is saved by Vanessa, a florist in New York City. As their relationship blossoms, he discovers humans actually eat honey, and subsequently decides to sue them.",
    releaseDate: "2007",
    image: "images/bee-movie.jpg",
    video: "https://www.youtube.com/embed/VONRQMx78YI?controls=0&rel=0&autoplay=1&showinfo=0",
    price: 0.49,
  },

];